[package]
name = "linear_simulations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beryllium = "0.13.0"
gl33 = "0.2.1"
imagine = "0.5.1"
ultraviolet = "0.9.2"
glfw = "0.54.0"
